[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
lib_compat_mode = off
lib_archive = no
;build_type = debug
; build_src_filter = +<*> -<.git/> -<.svn/>
build_flags =
  ;   -DportREMOVE_STATIC_QUALIFIER
 ; -DconfigUSE_TRACE_FACILITY=1
 ; -DconfigUSE_STATS_FORMATTING_FUNCTIONS=1
  ;   -DconfigGENERATE_RUN_TIME_STATS=1
  -I./src/cubemx/inc
;  -D UART1_DEBUG=1
;  -D MONITOR_TASK=1
;     -Wl,--undefined=uxTopUsedPriority
;     -D FREERTOS
;     -D FREERTOS_USE_TRACE_FACILITY=1
;     -ffunction-sections
;     -fdata-sections
;     -fno-omit-frame-pointer
;     ${env.build_flags}
debug_build_flags =
  ;   -DportREMOVE_STATIC_QUALIFIER
	; -DconfigUSE_TRACE_FACILITY=1
	; -DconfigUSE_STATS_FORMATTING_FUNCTIONS=1
  ;   -DconfigGENERATE_RUN_TIME_STATS=1
	; -D DEBUG
	; -O0
	; -g3
  ;   -gdwarf-2
  	-D FREERTOS
     ${env.build_flags}
monitor_speed = 115200
debug_tool = stlink
debug_svd_path = ${platformio.platforms_dir}/ststm32/misc/svd/STM32F103xx.svd
debug_server =
  openocd
  -f interface/stlink.cfg
  -f target/stm32f1x.cfg
  -c "reset_config srst_only"
  -c "stm32f1x.cpu configure -event gdb-halt \"mww 0xE000EDF0 0xA05F0001\""
; board_build.stm32cube.custom_system_setup = yes
; board_build.stm32cube.system_file = system_stm32f1xx.c
; upload_flags = -c set CPUTAPID 0x2ba01477
; debug_server =
; 	openocd
; 	-s /usr/share/openocd/scripts
; 	-f interface/stlink.cfg
; 	-c "transport select hla_swd"
; 	-c "set CPUTAPID 0x2ba01477"
; 	-f target/stm32f1x.cfg
; 	-c "reset_config none"
; board_debug.openocd_extra_args =
; 	-c "set CPUTAPID 0x2ba01477"
; lib_deps =
;   lib/freertos
;   lib/modbus
;lib_dir = lib

; lib_extra_dirs = todo extraFreeRTOS
;     /common/libraries
;     /iot/libraries