[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
;upload_protocol = dfu
;build_type = debug
;upload_flags = -c set CPUTAPID 0x2ba01477
build_flags =
  -I./src/cubemx/inc
  -I./src/cubemx/USB_DEVICE/App
	-I./src/cubemx/USB_DEVICE/Target
  -D USBD_USE_CDC
  -D MONITOR_TASK=1
debug_build_flags =
    ${env.build_flags}
    -D DEBUG
    -O0
    -g3
    -ggdb3
    -D FREERTOS
    -D FREERTOS_USE_TRACE_FACILITY=1
monitor_speed = 115200
debug_tool = stlink
debug_speed = 1000